[build]
  publish = "app"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
